name: qota
description: "Qota — plateforme universelle d'évaluation (services, lieux, figures publiques, User Items)."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Backend
  supabase_flutter: ^2.5.6

  # Routing
  go_router: ^14.2.0

  # State management
  flutter_riverpod: ^2.5.1

  # UI / UX
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1

  # Utils
  intl: ^0.20.2
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true # active la génération l10n depuis lib/l10n/*.arb

  assets:
    - assets/icons/
